### ISSUE TITLE
usage of pclmul may need SSE4.1

### ISSUE THREAD

**Issue by olafhering** [xavierleroy/cryptokit#32]
1267f4db07d33448afe0f550986ef8883000f4a5 fails to build on [SLES12 x86_64](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-cryptokit):

````
[   36s] + dune build --verbose --for-release-of-packages=cryptokit -j6 @install
....
[   37s] Command [30] exited with code 1:
[   37s] $ (cd _build/default/src && /usr/bin/gcc-4.8 -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -fno-builtin-memcmp -pthread -Werror=implicit-function-declaration -Werror=return-type -Wno-deprecated-declarations -fPIC -pipe -D_FILE_OFFSET_BITS=64 -DCAML_NAME_SPACE -DHAVE_ZLIB -maes -mpclmul -g -I /usr/lib64/ocaml -I /usr/lib64/ocaml/zarith -o pclmul.o -c pclmul.c)
[   37s] In file included from pclmul.c:24:0:
[   37s] /usr/lib64/gcc/x86_64-suse-linux/4.8/include/smmintrin.h:31:3: error: #error "SSE4.1 instruction set not enabled"
[   37s]  # error "SSE4.1 instruction set not enabled"
[   37s]    ^
````

`smmintrin.h` looks different in gcc7, perhaps this is a bug in gcc 4.8.

**Comment by xavierleroy** [comment]
Actually, the `#include <smmintrin.h>` in pclmul.c does refer to SSE4.1, but it is no longer necessary.  (It was in an earlier version of the code that used SSE4.1 instructions...)  Expect a fix soon.

**Comment by xavierleroy** [comment]
Commit 3ab75d3 should fix this issue.  Could you give it a try?

**Comment by olafhering** [comment]
Yes, this compiles now. Thank you.

**Comment by bguil** [comment]
I still have an error `#  # error "SSE4.1 instruction set not enabled"` with a fresh install of cryptokit 1.17.

The problem is fixed by 3ab75d393b0cd52d48cb000daf1b3882b8118e81 but this commit is not in 1.17.
Can you publish the 1.18 version which is ready in the code to solve this?

**Comment by David4x** [comment]
I also have this same issue but I am using opan and OCaml and that package manager is pulling from 

https://github.com/xavierleroy/cryptokit/archive/release117.tar.gz

This tar file does not contain the fix that removes  the #include <smmintrin.h> in pclmul.c file.

Can you please update the tar file with the latest versions of the code ASAP please?
